# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

test_comp = Company.create(name: "Vandelay Industries")

employee_names = %w(Rick\ Thomas Torey\ Hickman Andrew\ McGregor Tommy\ Wiseau Sandy\ Metz Marc\ Andreessen Bill\ Atkinson Kent\ Beck Tim\ Berners-Lee Grace\ Hopper Sabeer\ Bhatia Matt\ Mullenweg Brendan\ Eich Martin\ Fowler)
employee_emails = %w(rick@shinehardt.com torey@shinehardt.com andrew@shinehardt.com tommy@shinehardt.com smetz@pragmatic.com marc@mosaic.com batkinson@hypercard.com kbeck@facebook.com tim@theinternet.com grace@hopalong.com sbhatia1970@hotmail.com matt@mat.tt beich@js.net agile@programmi.ng)
employee_names.each_with_index do |name, x|
  test_comp.employees << Employee.create(name: name, email: employee_emails[x], password: "password")
end

# Challenges
##############################################################


challenge_titles = [
  "Sum of Multiples of 3 and 5",
  "Even Fibonacci Numbers",
  "Largest Prime Factor",
  "Largest Palindrome Product",
  "Smallest multiple",
  "Sum square difference",
  "10,001st Prime",
  "Largest product in a series"
]

challenge_descriptions = [
  "If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.  Find the sum of all the multiples of 3 or 5 below 1000.",
  "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: '1, 2, 3, 5, 8, 13, 21, 34, 55, 89,...'.  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.",
  "The prime factors of 13195 are 5, 7, 13 and 29.  What is the largest prime factor of the number 600851475143?",
  "A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 99.  Find the largest palindrome made from the product of two 3-digit numbers.",
  "2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.  What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?",
  "The sum of the squares of the first ten natural numbers is 12 + 22 + ... + 102 = 385.  The square of the sum of the first ten natural numbers is (1 + 2 + ... + 10)2 = 552 = 3025.  Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 - 385 = 2640.  Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.",
  "By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.  What is the 10,001st prime number?",
  "Find the greatest product of five consecutive digits in the 1000-digit number:

73167176531330624919225119674426574742355349194934
96983520312774506326239578318016984801869478851843
85861560789112949495459501737958331952853208805511
12540698747158523863050715693290963295227443043557
66896648950445244523161731856403098711121722383113
62229893423380308135336276614282806444486645238749
30358907296290491560440772390713810515859307960866
70172427121883998797908792274921901699720888093776
65727333001053367881220235421809751254540594752243
52584907711670556013604839586446706324415722155397
53697817977846174064955149290862569321978468622482
83972241375657056057490261407972968652414535100474
82166370484403199890008895243450658541227588666881
16427171479924442928230863465674813919123162824586
17866458359124566529476545682848912883142607690042
24219022671055626321111109370544217506941658960408
07198403850962455444362981230987879927244284909188
84580156166097919133875499200524063689912560717606
05886116467109405077541002256983155200055935729725
71636269561882670428252483600823257530420752963450
"
]

challenge_codes = [
  "# def sum_of_multiples 
#
# end",
"# def sum_of_evens
#
# end",
"# def largest_prime_factor
#
# end",
"# def largest_palindrome
#
# end",
"# def smallest_divisible_positive
#
# end",
"# def diff_sum_squares
#
# end",
"# def ten_thousand_first_prime
#
# end",
"# def five_consec_product 
#
# end"
]

public_or_not = [true, false]

challenge_titles.length.times do |num|
  challenge = Challenge.new(title: challenge_titles[num], description: challenge_descriptions[num], code: challenge_codes[num], public: public_or_not.sample)
  test_comp.challenges << challenge
  challenge.author = test_comp.employees.sample
  challenge.save!
end

# Topics
#############################################################

topics = %w(Bits\ and\ Bytes Data\ Structures Scripting/Regexes Object-Oriented\ Design Git Rails Carrierwave OAuth Jasmine CoffeeScript Travis\ CI HAML YAML MongoDB)
topics.each do |topic|
  topic = Topic.new(name: topic)
  test_comp.topics << topic
  topic.save
end
# Feedback Questions

#############################################################

feedback_questions = [
  "Was the candidate receptive to feedback?",
  "Culture fit?  Would I have a beer/etc. with this person?",
  "What technologies are most interesting to the candidate, and why?",
  "Which tech blogs does the candidate read?",
  "Did the candidate ask questions and check assumptions first? Or just dive into the given challenge?",
  "How was the balance of talk between interviewer and interviewee?",
  "Did the candidate display a good grasp of fundamentals?",
  "How were the candidate's work habits (use of branches, TDD, etc.)?",
  "Did the candidate display clear communication?"
]

feedback_questions.each do |q|
  test_comp.feedback_questions << FeedbackQuestion.create(prompt: q)
end
